# Generated by Django 3.0.3 on 2020-03-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('teacher', 'teacher permisions')]},
        ),
    ]
